service: days-ai-chat-backend

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'ap-south-1'}
  memorySize: 1024
  timeout: 25
  environment:
    NODE_ENV: ${env:NODE_ENV}
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRE: ${env:JWT_EXPIRE}
    FASTAPI_URL: ${env:FASTAPI_URL}
    CORS_ORIGIN: ${env:CORS_ORIGIN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "arn:aws:logs:*:*:*"

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
      JWT_SECRET: ${env:JWT_SECRET}
      JWT_EXPIRE: ${env:JWT_EXPIRE}
      FASTAPI_URL: ${env:FASTAPI_URL}
      CORS_ORIGIN: ${env:CORS_ORIGIN}
  
  health:
    handler: lambda.healthHandler
    events:
      - httpApi:
          path: /health
          method: GET
    environment:
      CORS_ORIGIN: ${env:CORS_ORIGIN}

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  
  serverless-offline:
    httpPort: 5000
    lambdaPort: 3002
    noPrependStageInUrl: true
  
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
    concurrency: 10
